services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"

  adminer:
    depends_on:
      - db
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
